// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counters.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCounter = `-- name: CreateCounter :one
INSERT INTO
  COUNTERS (ID, USER_ID, NAME)
VALUES
  ($1, $2, $3)
RETURNING
  id, user_id, name, visibility, edit_policy, created_at, updated_at
`

type CreateCounterParams struct {
	ID     uuid.UUID  `json:"id"`
	UserID *uuid.UUID `json:"user_id"`
	Name   string     `json:"name"`
}

func (q *Queries) CreateCounter(ctx context.Context, arg CreateCounterParams) (Counter, error) {
	row := q.db.QueryRow(ctx, createCounter, arg.ID, arg.UserID, arg.Name)
	var i Counter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Visibility,
		&i.EditPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCounter = `-- name: DeleteCounter :exec
DELETE FROM COUNTERS
WHERE
  ID = $1
`

func (q *Queries) DeleteCounter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCounter, id)
	return err
}

const getCounter = `-- name: GetCounter :one
SELECT
  id, user_id, name, visibility, edit_policy, created_at, updated_at
FROM
  COUNTERS
WHERE
  ID = $1
LIMIT
  1
`

func (q *Queries) GetCounter(ctx context.Context, id uuid.UUID) (Counter, error) {
	row := q.db.QueryRow(ctx, getCounter, id)
	var i Counter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Visibility,
		&i.EditPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCounterStats = `-- name: GetCounterStats :one
WITH
  AGGR AS (
    SELECT
      SUM(VALUE) AS TOTAL,
      MIN(RECORDED_AT) AS FIRST_DATE
    FROM
      DATA
    WHERE
      COUNTER_ID = $1
  ),
  TIMECALC AS (
    SELECT
      TOTAL,
      FIRST_DATE,
      CEIL(
        EXTRACT(
          EPOCH
          FROM
            (NOW() - FIRST_DATE)
        ) / 86400.0
      ) AS DAYS
    FROM
      AGGR
    WHERE
      FIRST_DATE IS NOT NULL
  )
SELECT
  CT.TOTAL,
  CT.DAYS,
  (CT.TOTAL / COALESCE(CT.DAYS, 1))::float AS AVG
FROM
  TIMECALC CT
`

type GetCounterStatsRow struct {
	Total int64   `json:"total"`
	Days  float64 `json:"days"`
	Avg   float64 `json:"avg"`
}

func (q *Queries) GetCounterStats(ctx context.Context, counterID uuid.UUID) (GetCounterStatsRow, error) {
	row := q.db.QueryRow(ctx, getCounterStats, counterID)
	var i GetCounterStatsRow
	err := row.Scan(&i.Total, &i.Days, &i.Avg)
	return i, err
}

const getCounterStatsSince = `-- name: GetCounterStatsSince :one
WITH
  AGGR AS (
    SELECT
      SUM(VALUE) AS TOTAL,
      MIN(RECORDED_AT) AS FIRST_DATE
    FROM
      DATA
    WHERE
      COUNTER_ID = $1
      AND /* sql-formatter-disable */
      EXTRACT(year from RECORDED_AT) >= $2::int
      /* sql-formatter-enable */
  ),
  TIMECALC AS (
    SELECT
      TOTAL,
      FIRST_DATE,
      CEIL(
        EXTRACT(
          EPOCH
          FROM
            (NOW() - FIRST_DATE)
        ) / 86400.0
      ) AS DAYS
    FROM
      AGGR
    WHERE
      FIRST_DATE IS NOT NULL
  )
SELECT
  CT.TOTAL,
  CT.DAYS,
  (CT.TOTAL / COALESCE(CT.DAYS, 1))::float AS AVG
FROM
  TIMECALC CT
`

type GetCounterStatsSinceParams struct {
	CounterID uuid.UUID `json:"counter_id"`
	FromYear  int32     `json:"from_year"`
}

type GetCounterStatsSinceRow struct {
	Total int64   `json:"total"`
	Days  float64 `json:"days"`
	Avg   float64 `json:"avg"`
}

func (q *Queries) GetCounterStatsSince(ctx context.Context, arg GetCounterStatsSinceParams) (GetCounterStatsSinceRow, error) {
	row := q.db.QueryRow(ctx, getCounterStatsSince, arg.CounterID, arg.FromYear)
	var i GetCounterStatsSinceRow
	err := row.Scan(&i.Total, &i.Days, &i.Avg)
	return i, err
}

const listCounters = `-- name: ListCounters :many
SELECT
  id, user_id, name, visibility, edit_policy, created_at, updated_at
FROM
  COUNTERS
ORDER BY
  ID
`

func (q *Queries) ListCounters(ctx context.Context) ([]Counter, error) {
	rows, err := q.db.Query(ctx, listCounters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Counter
	for rows.Next() {
		var i Counter
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Visibility,
			&i.EditPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountersByUser = `-- name: ListCountersByUser :many
SELECT
  id, user_id, name, visibility, edit_policy, created_at, updated_at
FROM
  COUNTERS
WHERE
  USER_ID = $1
ORDER BY
  ID
`

func (q *Queries) ListCountersByUser(ctx context.Context, userID *uuid.UUID) ([]Counter, error) {
	rows, err := q.db.Query(ctx, listCountersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Counter
	for rows.Next() {
		var i Counter
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Visibility,
			&i.EditPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCounter = `-- name: UpdateCounter :one
UPDATE COUNTERS
SET
  NAME = $2,
  USER_ID = $3
WHERE
  ID = $1
RETURNING
  id, user_id, name, visibility, edit_policy, created_at, updated_at
`

type UpdateCounterParams struct {
	ID     uuid.UUID  `json:"id"`
	Name   string     `json:"name"`
	UserID *uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateCounter(ctx context.Context, arg UpdateCounterParams) (Counter, error) {
	row := q.db.QueryRow(ctx, updateCounter, arg.ID, arg.Name, arg.UserID)
	var i Counter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Visibility,
		&i.EditPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
