// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: data.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createData = `-- name: CreateData :one
INSERT INTO
    DATA (ID, COUNTER_ID, VALUE, RECORDED_AT)
VALUES
    ($1, $2, $3, $4)
RETURNING
    id, counter_id, value, recorded_at, created_at, updated_at
`

type CreateDataParams struct {
	ID         uuid.UUID          `json:"id"`
	CounterID  uuid.UUID          `json:"counter_id"`
	Value      int32              `json:"value"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
}

func (q *Queries) CreateData(ctx context.Context, arg CreateDataParams) (Datum, error) {
	row := q.db.QueryRow(ctx, createData,
		arg.ID,
		arg.CounterID,
		arg.Value,
		arg.RecordedAt,
	)
	var i Datum
	err := row.Scan(
		&i.ID,
		&i.CounterID,
		&i.Value,
		&i.RecordedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteData = `-- name: DeleteData :exec
DELETE FROM DATA
WHERE
    ID = $1
`

func (q *Queries) DeleteData(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteData, id)
	return err
}

const getData = `-- name: GetData :one
SELECT
    id, counter_id, value, recorded_at, created_at, updated_at
FROM
    DATA
WHERE
    ID = $1
LIMIT
    1
`

func (q *Queries) GetData(ctx context.Context, id uuid.UUID) (Datum, error) {
	row := q.db.QueryRow(ctx, getData, id)
	var i Datum
	err := row.Scan(
		&i.ID,
		&i.CounterID,
		&i.Value,
		&i.RecordedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listData = `-- name: ListData :many
SELECT
    id, counter_id, value, recorded_at, created_at, updated_at
FROM
    DATA
ORDER BY
    ID
`

func (q *Queries) ListData(ctx context.Context) ([]Datum, error) {
	rows, err := q.db.Query(ctx, listData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Datum
	for rows.Next() {
		var i Datum
		if err := rows.Scan(
			&i.ID,
			&i.CounterID,
			&i.Value,
			&i.RecordedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataByCounter = `-- name: ListDataByCounter :many
SELECT
    id, counter_id, value, recorded_at, created_at, updated_at
FROM
    DATA
WHERE
    COUNTER_ID = $1
ORDER BY
    ID
`

func (q *Queries) ListDataByCounter(ctx context.Context, counterID uuid.UUID) ([]Datum, error) {
	rows, err := q.db.Query(ctx, listDataByCounter, counterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Datum
	for rows.Next() {
		var i Datum
		if err := rows.Scan(
			&i.ID,
			&i.CounterID,
			&i.Value,
			&i.RecordedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataByCounterSince = `-- name: ListDataByCounterSince :many
SELECT
    id, counter_id, value, recorded_at, created_at, updated_at
FROM
    DATA
WHERE
    COUNTER_ID = $1
    AND /* sql-formatter-disable */
    EXTRACT(year from RECORDED_AT) >= $2::int
    /* sql-formatter-enable */
ORDER BY
    ID
`

type ListDataByCounterSinceParams struct {
	CounterID uuid.UUID `json:"counter_id"`
	FromYear  int32     `json:"from_year"`
}

func (q *Queries) ListDataByCounterSince(ctx context.Context, arg ListDataByCounterSinceParams) ([]Datum, error) {
	rows, err := q.db.Query(ctx, listDataByCounterSince, arg.CounterID, arg.FromYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Datum
	for rows.Next() {
		var i Datum
		if err := rows.Scan(
			&i.ID,
			&i.CounterID,
			&i.Value,
			&i.RecordedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataFeed = `-- name: ListDataFeed :many
SELECT
    id, counter_id, value, recorded_at, created_at, updated_at
FROM
    DATA
ORDER BY
    RECORDED_AT DESC,
    ID DESC
LIMIT
    $1
OFFSET
    $2
`

type ListDataFeedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDataFeed(ctx context.Context, arg ListDataFeedParams) ([]Datum, error) {
	rows, err := q.db.Query(ctx, listDataFeed, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Datum
	for rows.Next() {
		var i Datum
		if err := rows.Scan(
			&i.ID,
			&i.CounterID,
			&i.Value,
			&i.RecordedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataSince = `-- name: ListDataSince :many
SELECT
    id, counter_id, value, recorded_at, created_at, updated_at
FROM
    DATA
WHERE
    /* sql-formatter-disable */
    EXTRACT(year from RECORDED_AT) >= $1::int
    /* sql-formatter-enable */
ORDER BY
    ID
`

func (q *Queries) ListDataSince(ctx context.Context, fromYear int32) ([]Datum, error) {
	rows, err := q.db.Query(ctx, listDataSince, fromYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Datum
	for rows.Next() {
		var i Datum
		if err := rows.Scan(
			&i.ID,
			&i.CounterID,
			&i.Value,
			&i.RecordedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
