// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Counter struct {
	ID        uuid.UUID          `json:"id"`
	UserID    *uuid.UUID         `json:"user_id"`
	Name      string             `json:"name"`
	SoftReset pgtype.Timestamptz `json:"soft_reset"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Datum struct {
	ID         uuid.UUID          `json:"id"`
	CounterID  uuid.UUID          `json:"counter_id"`
	Value      int32              `json:"value"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Group struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type GroupUser struct {
	UserID   uuid.UUID          `json:"user_id"`
	GroupID  uuid.UUID          `json:"group_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Password  string             `json:"-"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
