CREATE TYPE COUNTER_VISIBILITY AS ENUM('global', 'group', 'private');


CREATE TYPE COUNTER_EDIT_POLICY AS ENUM('everyone', 'owner_only');


CREATE TABLE GROUPS (
    ID UUID PRIMARY KEY,
    NAME TEXT NOT NULL UNIQUE,
    CREATED_AT TIMESTAMPTZ DEFAULT now() NOT NULL,
    UPDATED_AT TIMESTAMPTZ DEFAULT now() NOT NULL
);


CREATE TABLE USERS (
    ID UUID PRIMARY KEY,
    USERNAME TEXT NOT NULL UNIQUE,
    PASSWORD TEXT NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT now() NOT NULL,
    UPDATED_AT TIMESTAMPTZ DEFAULT now() NOT NULL
);


CREATE TABLE GROUP_USERS (
    USER_ID UUID NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
    GROUP_ID UUID NOT NULL REFERENCES GROUPS (ID) ON DELETE CASCADE,
    JOINED_AT TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (USER_ID, GROUP_ID)
);


CREATE INDEX IDX_USER_GROUPS_USER_ID ON GROUP_USERS (USER_ID);


CREATE INDEX IDX_USER_GROUPS_GROUP_ID ON GROUP_USERS (GROUP_ID);


CREATE TABLE COUNTERS (
    ID UUID PRIMARY KEY,
    USER_ID UUID REFERENCES USERS (ID) ON DELETE CASCADE,
    NAME TEXT NOT NULL UNIQUE,
    VISIBILITY COUNTER_VISIBILITY NOT NULL DEFAULT 'private',
    EDIT_POLICY COUNTER_EDIT_POLICY NOT NULL DEFAULT 'owner_only',
    CREATED_AT TIMESTAMPTZ DEFAULT now() NOT NULL,
    UPDATED_AT TIMESTAMPTZ DEFAULT now() NOT NULL
);


CREATE INDEX IDX_COUNTERS_USER_ID ON COUNTERS (USER_ID);


CREATE TABLE DATA (
    ID UUID PRIMARY KEY,
    COUNTER_ID UUID NOT NULL REFERENCES COUNTERS (ID) ON DELETE CASCADE,
    VALUE INTEGER NOT NULL,
    RECORDED_AT TIMESTAMPTZ DEFAULT now() NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT now() NOT NULL,
    UPDATED_AT TIMESTAMPTZ DEFAULT now() NOT NULL
);


CREATE INDEX IDX_DATA_RECORDED_AT ON DATA (RECORDED_AT);


CREATE INDEX IDX_DATA_COUNTER_ID ON DATA (COUNTER_ID);
